### PR TITLE
Fix port

### PR DESCRIPTION
**Pull request by shyim**
The port is 8080 and not 80

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Thanks!

Just checking, It might be enough to change the container port, right?

**Comment by shyim** [comment]
Yep. Have it so running on my k3s

**Comment by JC5** [comment]
OK, so why did you update both port mentions?

**Comment by juansalvatella** [comment]
> Thanks!
> 
> Just checking, It might be enough to change the container port, right?

The firefly-iii service needs to be updated as well as it's sending the requests to port 80 (and it should be sent to port 8080).

**Comment by JC5** [comment]
Ok so which one is it? Should I merge #1 or #3?

**Comment by juansalvatella** [comment]
I'm sorry I didn't realize before there was a pull request tackling this
issue. Both will work.

On #1 the exposed port to access Firefly III will be 8080 and on #3 it will
be 80. In my case, I prefer port 80 for firefly-iii as I created a manifest
for the firefly-importer and it's exposed on port 8080.

**Comment by JC5** [comment]
Fair.

**Pull request closed without merging**
